name: CI Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest
    container: strikef/swpp-ci

    steps:
    - uses: actions/checkout@v3

    - name: Build Alive2
      run: ./.github/scripts/build_alive2.sh

    - name: Configure CMake
      run: cmake -GNinja -Bbuild  1849  cmake -GNinja -Bbuild -DALIVE2_BINARY_DIR=~./alive2/build/
      
    - name: Build
      run: cmake --build build --target swpp-compiler

    - name: Test
      run: ctest --test-dir build

