name: CI Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest
    container: strikef/swpp-ci

    steps:
    - uses: actions/checkout@v3

    - name: Cache Alive2 build
      id: cache-alive2
      uses: actions/cache@v3
      with:
        path: ./alive2/build
        key: ${{ runner.os }}-alive2-${{ hashFiles('.github/scripts/build_alive2.sh') }}

    - if: ${{ steps.cache-alive2.outputs.cache-hit != 'true' }}
      name: Build Alive2
      run: ./.github/scripts/build_alive2.sh

    - name: Configure CMake
      run: cmake -GNinja -Bbuild -DALIVE2_BINARY_DIR=~./alive2/build/
      
    - name: Build
      run: cmake --build build --target swpp-compiler

    - name: Unit Test
      run: ctest --test-dir build

    - name: Test Benchmark Compilation
      run: ./.github/scripts/test_benchmark_compilation.sh ./alive2/build/
